  php:
    image: ${PROJET_NAME}-php
    container_name: ${INSTALL_NAME}-${USER_NAME}-php
    environment:
      - USER_NAME=${USER_NAME}
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - PROJET_NAME=${PROJET_NAME}
    volumes:
      - ./${PROJET_NAME}:/${PROJET_NAME}
      - /home/${USER_NAME}/.ssh:/home/${USER_NAME}/.ssh
      